const IMAGES={
    arrow_up: require('../assets/Icons/green/arrow_up.png'),
    AccountBook: require('../assets/Icons/green/AccountBook.png'),
    arrowIcon: require('../assets/Icons/green/arrowIcon.png'),
    BankTransfer: require('../assets/Icons/green/BankTransfer.png'),
    calendar: require('../assets/Icons/green/calendar.png'),
    centersettingsIcon: require('../assets/Icons/green/centersettingsIcon.png'),
    changeProfileIcon: require('../assets/Icons/green/changeProfileIcon.png'),
    Electricity: require('../assets/Icons/green/Electricity.png'),
    Ellipse: require('../assets/Icons/green/Ellipse.png'),
    expandBelow: require('../assets/Icons/green/expandBelow.png'),
    footerHome: require('../assets/Icons/green/footerHome.png'),
    iconfooterScan: require('../assets/Icons/green/iconfooterScan.png'),
    InterestRate: require('../assets/Icons/green/InterestRate.png'),
    Landline: require('../assets/Icons/green/Landline.png'),
    Load: require('../assets/Icons/green/Load.png'),
    mobile: require('../assets/Icons/green/mobile.png'),
    MoneyCheque: require('../assets/Icons/green/MoneyCheque.png'),
    nepalFlagIcon: require('../assets/Icons/green/nepalFlagIcon.png'),
    notification: require('../assets/Icons/green/notification.png'),
    passwordSet: require('../assets/Icons/green/passwordSet.png'),
    phonebook: require('../assets/Icons/green/phonebook.png'),
    phoneRinging: require('../assets/Icons/green/phoneRinging.png'),
    profile: require('../assets/Icons/green/profile.png'),
    promoCodeIcon: require('../assets/Icons/green/promoCodeIcon.png'),
    setFingerprintIcon: require('../assets/Icons/green/setFingerprintIcon.png'),
    shrinkDown: require('../assets/Icons/green/shrinkDown.png'),
    Statement: require('../assets/Icons/green/Statement.png'),
    screenheader: require('../assets/Icons/green/screenheader.png'),
    securityCodeIcon: require('../assets/Icons/green/securityCodeIcon.png'),
    Television: require('../assets/Icons/green/Television.png'),
    termsOfServices: require('../assets/Icons/green/termsOfServices.png'),
    Topup: require('../assets/Icons/green/Topup.png'),
    Transfer: require('../assets/Icons/green/Transfer.png'),
    verificationOTP: require('../assets/Icons/green/verificationOTP.png'),
    Water: require('../assets/Icons/green/Water.png'),
  
    //general
    call: require('../assets/Icons/general/call.png'),
    checkIn: require('../assets/Icons/general/checkIn.png'),
    investInGold: require('../assets/Icons/general/investInGold.png'),
    query: require('../assets/Icons/general/query.png'),
    account: require('../assets/Icons/general/account.png'),
    arrow_down: require('../assets/Icons/general/arrow_down.png'),
    bell: require('../assets/Icons/general/bell.png'),
    eyes: require('../assets/Icons/general/eyes.png'),
    eyesInPassword: require('../assets/Icons/general/eyesInPassword.png'),
    eyesOpen: require('../assets/Icons/general/eyesOpen.png'),
    fingerPrintIcon: require('../assets/Icons/general/fingerPrintIcon.png'),
    footerHistory: require('../assets/Icons/general/footerHistory.png'),
    footerOffers: require('../assets/Icons/general/footerOffers.png'),
    footerProfile: require('../assets/Icons/general/footerProfile.png'),
    history: require('../assets/Icons/general/history.png'),
    shareQR: require('../assets/Icons/general/shareQR.png'),
    ticketsIcon: require('../assets/Icons/general/ticketsIcon.png'),
    toggle: require('../assets/Icons/general/toggle.png'),
    VectortickMark: require('../assets/Icons/general/VectortickMark.png'),
  
  
    
    // images
    centerImage: require('../assets/Images/centerImage.png'),
    leftImage: require('../assets/Images/leftImage.png'),
    QRcode: require('../assets/Images/QRcode.png'),
    rightImage: require('../assets/Images/rightImage.png'),
    satvabLogo: require('../assets/Images/satvabLogo.jpg'),
  
    //for register and login
    ellipses1: require('../assets/Images/ellipses1.png'),
    ellipses2: require('../assets/Images/ellipses2.png'),
    registerEllipse: require('../assets/Images/registerEllipse.png'),
    
  
  }
  export default IMAGES;